### ISSUE TITLE
docker kuberneter monitoring tool 

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#100]
we need to use a docker kuberneter monitoring tool are we using to visualize the stats of each ova

**Comment by pranaysahith** [comment]
@GINAGC 
I am reusing the solution of elasticsearch and grafana we developed here - https://github.com/k8-proxy/icap-infrastructure/issues/10
currently there is an issue with mounting host volume on grafana pods and I am working on fixing it.
