### ISSUE TITLE
Test 4 OVAs and review documentation as an end user

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#106]
Follow the steps here: https://github.com/k8-proxy/GW-proxy

1.- Deploy the 4 OVAs
2.- Validate documentation
3.- Make sure everything is correctly documented
4.- Provide feedback on areas missed in the documentation
5.- Provide feedback on areas that can be improved: steps that can be automated i

**Comment by dtollaku** [comment]
Nader will test on ESXI server of Egirna, till will purchase the one of GW.
