### ISSUE TITLE
Review existing diagrams and add any missed information.

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#109]
Samarth, Baker,

Please do a cross review for the existing diagrams for the websites and add any feedback or updates needed here: 
1.- @samarthdd to review the 4 OVAs diagram created by Baker: https://github.com/k8-proxy/GW-proxy/issues/98#issuecomment-731328474
2.- @baker371 to review the2 website diagrams created by Samarth: https://glasswallsolu-qbp1117.slack.com/archives/C01ETT9U38A/p1605771023028300?thread_ts=1605748598.026900&cid=C01ETT9U38A

Thanks

**Comment by samarthdd** [comment]
@baker371  Review comments for https://github.com/k8-proxy/GW-proxy/issues/98#issuecomment-731328474

The diagram looks good according to steps given in git repo.

Here are few observation.

Glasswall Engineering OVA depends on ICAP ova, dependency not shown in diagram
2. Can remove hardcoded IP in first diagram.

3. Once OVA is imported, go to Settings>Network>Adapter 2 in all vms, it shoulbe either verify Network Adapter or configure Network Adapter , when layman look at the diagram , just “Go” doesnt tell anything. So either after verify/configure , VM will be started.

4. Better to menation VM command line and local terminal to be more clear
5. Check Ip adddress should be replaced by just IP address which is value passing in UML components

6. in Diagram 3,4 under browser or above arrow, url http://minio.server , http://minio.server.local.glasswall-icap.com/ respectively can be mentioned for better understanding.

7. Can mention <VM IPADDRESS> minio.server or update minio.server IP in diagram 3

8. Diagram 1, it should be start not open for ICAP server VM

**Comment by baker371** [comment]
![ICAP_server_OVA](https://user-images.githubusercontent.com/8102313/100139642-d64dcc80-2ea0-11eb-90a2-46d0991a1336.png)

**Comment by baker371** [comment]
![Glasswall_Engineering_OVA](https://user-images.githubusercontent.com/8102313/100145166-f71a2000-2ea8-11eb-9a86-3238031b09eb.png)

**Comment by baker371** [comment]
![Minio_Server_OVA](https://user-images.githubusercontent.com/8102313/100146574-2d589f00-2eab-11eb-926c-307b162250e7.png)

**Comment by baker371** [comment]
![Minio_Proxy_OVA](https://user-images.githubusercontent.com/8102313/100151033-9f33e700-2eb1-11eb-98d6-a3742aa9824b.png)

**Comment by GINAGC** [comment]
@baker371, @samarthdd please upload the latest diagrams from both of you to here: https://github.com/k8-proxy/k8-proxy-documentation/blob/master/docs/flavors/flavor-ova/technical-architecture.md let me know once you send the PR. Thanks
