### ISSUE TITLE
Document how to migrate deployments from AWS to ESXi

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#118]
Patrick,

We want to find the easiest way to export all the running websites in AWS, export them to OVA and deploy that OVA in ESXi server:

https://k8-proxy.github.io/k8-proxy-documentation/docs/dashboards/websites/production/

**Comment by MariuszFerdyn** [comment]
Download: ovftool.exe from https://my.vmware.com/web/vmware/downloads/details?productId=614&downloadGroup=OVFTOOL420

Extract .OVA to .OVF:
`"C:\Program Files (x86)\VMware\VMware Workstation\OVFTool\ovftool.exe" glasswall-proxy.ova vmware.ovf `

Using text editor virtualbox-2.2 to vmx-07 in .OVF file:
`C:\Program Files (x86)\Notepad++\notepad++.exe" vmware.ovf`

Build machine using vmware.ovf and vmware.-disk1.vmdk

**Comment by azopat** [comment]
Notes are added here
https://github.com/k8-proxy/icap-infrastructure/blob/esxi-sow/README-esxi.md

**Comment by MariuszFerdyn** [comment]
You can use this script to do some automation on ovf file and fine tuning process:
```
#!/usr/bin/python3
#
# usage:
#        conv2vmx-ovf.py some-vm.ovf
#
# ref: http://www.cnblogs.com/eshizhan/p/3332020.html
#

import sys
fn = sys.argv[1]
fp = open(fn, 'rb').read()

fp = fp.replace(b'<vssd:VirtualSystemType>virtualbox-2.2', b'<vssd:VirtualSystemType>vmx-07')

fp = fp.replace(b'<rasd:Caption>ideController', b'<rasd:Caption>scsiController')
fp = fp.replace(b'<rasd:Description>IDE Controller', b'<rasd:Description>SCSI Controller')
fp = fp.replace(b'<rasd:ElementName>ideController', b'<rasd:ElementName>scsiController')
fp = fp.replace(b'<rasd:ResourceSubType>PIIX4', b'<rasd:ResourceSubType>lsilogic')
fp = fp.replace(b'<rasd:ResourceType>5', b'<rasd:ResourceType>6')

nfp = open('vmx_' + fn, 'wb')
nfp.write(fp)
```
