### ISSUE TITLE
Create CSV for glasswall solution website

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#122]
Create a CSV file that includes the path of the file, the name, and the format for all the documents on the website: https://glasswallsolutions.com/

Example attached.

**Comment by NourEddineX** [comment]
File uploaded
Preview: https://github.com/k8-proxy/aws-jmeter-test-engine/blob/glasswallsolutions.com/jmeter-icap/scripts/ICAP-Proxy-Site/glasswallsolutions.com_files.csv
Raw file: https://raw.githubusercontent.com/k8-proxy/aws-jmeter-test-engine/glasswallsolutions.com/jmeter-icap/scripts/ICAP-Proxy-Site/glasswallsolutions.com_files.csv
