### ISSUE TITLE
Create Support VM

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/GW-proxy#125]
The support VM, is going to be the VM where it hosts there components as of now:

1. DNS server.
2. RDP or similar server.
3. PKI server.

For now we would like to test out https://guacamole.apache.org/ as a method of providing an external client to the remote desktop of a GUI based Linux machine installed inside the ESXi server, typically Ubuntu.

**Comment by MariuszFerdyn** [comment]
Agree with @mahnouman to start with with Guacomole server, then we take it from there.
