### ISSUE TITLE
Build offline gov.uk website as OVA

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#129]
Either build from scratch or customize on top, please build this website: gov.uk as an offline website with example pdfs and similar. Then package that as an OVA.

**Comment by hongson1981** [comment]
Hi @GINAGC , @mahnouman , @NourEddineX 
Here is my solution : 
1. Clone(Copy) gov.uk website and save it as offline website
2. Create VM with Ubuntu OS + apache server
3. Deploy offline website on step 1 to VM under domain gov.uk.local

Deos this solution meet your expectation ?, any comment and addition ?

**Comment by mahnouman** [comment]
Relevant solution:
https://k8-mass-download.s3.eu-west-2.amazonaws.com/gov_Files.zip

**Comment by hongson1981** [comment]
Hi @mahnouman , @GINAGC 
Update progress
1. OVA file is already
2. Documentation is preparing, will be already tomorrow for testing
