### ISSUE TITLE
Testing Wordpress OVA

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/GW-proxy#133]
Test @hongson1981 provided instructions for the creation of an offline Wordpress OVA, the instructions are found here:
https://github.com/k8-proxy/GW-proxy/blob/master/OVAs-creation/create_export_import_wordpress_site.md

**Comment by svf97** [comment]
- entire documentation was followed through, and only 2 comments were found:
   - creating VM: 
     - run `sudo service apache2 start` **before** `sudo service apache2 reload`
   -  importing VM: 
     - run `ip a` **before** verifying/modifying "00-installer-config.yaml" so ethernets can be modified accordingly:
the image below shows result of `ip a`, which in this case the network interface is now `enp0s3`, as opposed to the yaml file that we are modifying, which is `ens160`
![image](https://user-images.githubusercontent.com/60857664/100744820-0b997380-33e7-11eb-93f1-0b7d942f3cd2.png)
![image](https://user-images.githubusercontent.com/60857664/100745043-5fa45800-33e7-11eb-83c1-1e918853ca63.png)

**Comment by hongson1981** [comment]
THanks @svf97 ,
Document is updated following your comments

**Comment by MaNe2020** [comment]
Great documentation indeed.
Created PR with few cosmetic changes:  https://github.com/k8-proxy/GW-proxy/pull/145

**Comment by GINAGC** [comment]
Thank you everyone! @svf97 , @MaNe2020 I am moving this to peer review, let me know if you have anything to add, if not, I will close it.
