### ISSUE TITLE
Create Linux-Desktop OVA

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/GW-proxy#135]
The purpose of this task is to create a Linux VM with GUI, typically Ubuntu. The idea is that this VM will be used as a way for the end user to test the solution, since it will have customization to add the used self signed digital certificates as trusted and custom hosts entries so it does not display the usual alerts.

**Comment by naderaly** [comment]
@mahnouman An ubuntu VM with GUI is installed on esxi02.glasswall-icap.com with name Client-Showcase with the following IP :
78.159.113.45/26
Also I have enabled remote desktop so It could be accessed from any windows via (Remote Desktop connection) 
username: glasswall & and the agreed password

**Comment by mahnouman** [comment]
Hello @naderaly 
Please install this certificate into the client machine and mark it as a trusted root certificate from browsers point of view:
-----BEGIN CERTIFICATE-----
MIIDvjCCAqagAwIBAgIIa3VJt1eLgRYwDQYJKoZIhvcNAQELBQAwZTELMAkGA1UE
BhMCVUsxDjAMBgNVBAgTBUVzc2V4MRcwFQYDVQQKEw5HVyBEZXZlbG9wbWVudDEU
MBIGA1UECxMLRGV2ZWxvcG1lbnQxFzAVBgNVBAMTDkdXIERldmVsb3BtZW50MB4X
DTIwMDkwODA5MTkwMFoXDTMwMDkwODA5MTkwMFowZTELMAkGA1UEBhMCVUsxDjAM
BgNVBAgTBUVzc2V4MRcwFQYDVQQKEw5HVyBEZXZlbG9wbWVudDEUMBIGA1UECxML
RGV2ZWxvcG1lbnQxFzAVBgNVBAMTDkdXIERldmVsb3BtZW50MIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKobrHfirIHK9VxqZ2ezA+dT0c03stu1TPjY
PYUwFZrwyejjWU8S3GREjSXO76dntRPr8tetzJShzMQikt55VcnAcZCcdzd1QK23
H/vlnncIwkqzCPIuV76FfzleT+rVFrl4MS03LY4j4uwrinEkjl/wvIXv64fyl0Cl
8ACvRcuunBapoUDkSdW1v1v2n6jiyF+Ob+xvczbiaRC/dITm00x81WQKGL66A/8C
QdSknLH6vcj91Sg5aUvNEB4wXhBctY73HOsV3j8qo379LdXxJwt1B1Y4WaWI3rS5
fEck7XmhW5OGvHEW4GJvh7/AjE7GoFYKB4n51oeDZfdafTdfsQIDAQABo3IwcDAP
BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBShDr/9+fHtWRQv+ww/3xuYmkGfWTAL
BgNVHQ8EBAMCAQYwEQYJYIZIAYb4QgEBBAQDAgAHMB4GCWCGSAGG+EIBDQQRFg94
Y2EgY2VydGlmaWNhdGUwDQYJKoZIhvcNAQELBQADggEBAHMdmsVvWp4unMF2h0H6
+RX+npWFLvjSmrQiLSWjmPykZQZhXeEtMU1pRP53z/BUKjxcozIDe+/rrp9jLA+3
gg5gUML5l/XuH/7ad0JBp9cu+G10hFK69hWID36jpzPPrAHdMc2rFETGpXuYw85b
8q3mJ95psrccQiGM/Jgr1sU+Mwz5f7Jpkg0nLWcmA/ORkBidWsK5ZWusfL7tglQE
y/S0g2yAG+SPbb54bH+N6c3gcHuBdlcGu5WW3ZHad0f2hLRMK/UaPbT1igcrxxur
AIB35OlLRDs3BUdmx+YD/DAqxITHVne7nEEstq84lK6VYBFBUzUQ6M50N6COrYBR
21w=
-----END CERTIFICATE-----

**Comment by naderaly** [comment]
@mahnouman done

**Comment by mahnouman** [comment]
Hello @naderaly 
Please set the Client machine browser default homepage to be:
http://support.local/welcome/

**Comment by mahnouman** [comment]
Hello @naderaly 
We need to configure the DNS settings of the server as 78.159.113.38 without other DNS entries.

**Comment by naderaly** [comment]
done & done

**Comment by mahnouman** [comment]
@naderaly
Correction: Please setup the browser homepage to be:
https://github.com/k8-proxy/ESXI-setup-server

And please install c-icap package

**Comment by mahnouman** [comment]
@naderaly 
Correction: This OVA name is Linux-Desktop

**Comment by mahnouman** [comment]
@naderaly 
Correction:
Keep the DNS as 8.8.8.8

**Comment by mahnouman** [comment]
@naderaly 
Correction: The browser homepage is:
https://github.com/k8-proxy/ESXI-setup-server/wiki

**Comment by naderaly** [comment]
Documentation posted here 
https://github.com/k8-proxy/GW-proxy/blob/master/OVAs-creation/Linux-Desktop.md
