### ISSUE TITLE
OVA creation enhancements ideas

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/GW-proxy#141]
Just a placeholder for upcoming issue.

From @MariuszFerdyn :
Delete unnecessary logs, keys and history (every command should be issued double):
```
sudo rm -f /etc/ssh/*.pub
sudo rm -f /etc/ssh/*.key
sudo logrotate --force /etc/logrotate.conf
history -c && history -w
```
Add firewall configuration....

**Comment by MariuszFerdyn** [comment]
1. Remove public keys. rm ~/.ssh/authorized_keys
2. Do not use LVM (like other's Cloud Provider - AWS, Azure)
3. Add first launch scripts that assk for a new password for glasswall user.
