### ISSUE TITLE
Populate offline Wordpress and create CSV file for it

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/GW-proxy#149]
Create a script of something to populate the [offline Wordpress](https://github.com/k8-proxy/GW-proxy/blob/master/OVAs-creation/create_export_import_wordpress_site.md) with content that is in the interest of CDR.
Then create a testing csv file, with content similar to the below format:
assets.publishing.service.gov.uk.glasswall-icap.com,/government/uploads/system/uploads/attachment_data/file/838650/Ministerial_Hospitality__April_to_June_2019.csv,csv
assets.publishing.service.gov.uk.glasswall-icap.com,/government/uploads/system/uploads/attachment_data/file/914195/CR_Find_Supplier_Invoices_over__25k_AUGUST_2020_-Copy.csv,csv
assets.publishing.service.gov.uk.glasswall-icap.com,/government/uploads/system/uploads/attachment_data/file/824483/July_2019_Consular_MI.csv,csv
assets.publishing.service.gov.uk.glasswall-icap.com,/government/uploads/system/uploads/attachment_data/file/651065/Management_information-schools-30_Sep_2017.csv,csv
assets.publishing.service.gov.uk.glasswall-icap.com,/government/uploads/system/uploads/attachment_data/file/821009/Chart17.csv,csv
assets.publishing.service.gov.uk.glasswall-icap.com,/government/uploads/system/uploads/attachment_data/file/916065/Management_information-state-funded_schools-latest_inspections_at_31_August_2020.csv,csv
assets.publishing.service.gov.uk.glasswall-icap.com,/government/uploads/system/uploads/attachment_data/file/861803/LA_level_data_in_year_2018_to_2019.csv,csv
assets.publishing.service.gov.uk.glasswall-icap.com,/government/uploads/system/uploads/attachment_data/file/492733/TSB_Transactions_Over_25k-December_15.csv,csv
assets.publishing.service.gov.uk.glasswall-icap.com,/government/uploads/system/uploads/attachment_data/file/667558/2017-12-06_HoL_HOSPITALITY_Quarterly_Return_July-_Sept.csv,csv
assets.publishing.service.gov.uk.glasswall-icap.com,/government/uploads/system/uploads/attachment_data/file/544684/Tranparency_data_2015-2016.csv,csv

**Comment by nirvishek** [comment]
@mahnouman I have created the script as mentioned to automate populating the local wordpress, I need some clarification on the testing csv part. 
This is what i understood from the format provided: SOURCE_URL_OR_BUCKET, FILE_NAME_WITH_PATH, FILE_TYPE
What exactly has to be done with this csv? Are we talking about importing data from this csv and creating post using that or uploading the files mentioned in the csv which again seems to be csv?
