### ISSUE TITLE
Pre-Prod Setup

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/GW-proxy#153]
Using esxi02 to deploy the tested solution components for showcasing, the components are:

OVA Name | Owner | Status | IP Address
------------ | ------------- | ------------- | -------------
preprod-ICAP-Server-1 | @svf97 | Done | 78.159.113.47
preprod-ICAP-Server-2 | @svf97 | Done | 78.159.113.46
preprod-HAProxy-ICAP | @samarthdd | Done | 78.159.113.42
preprod-Proxy-1 | @azopat   | Done  | 78.159.113.35
preprod-Proxy-2 | @azopat   | Done  | 78.159.113.36
preprod-HAProxy-Web | @naderaly | Done | 78.159.113.56
preprod-Wordpress | @nirvishek  | Done | 78.159.113.39
preprod-MinIO| @naderaly | Done | 78.159.113.43
preprod-Gov-UK | @NourEddineX  | Done  | 78.159.113.33
preprod-Shared-Storage | @top-dev-mania | Done   | 78.159.113.45
preprod-Linux-Desktop  | @top-dev-mania | Done  | 78.159.113.48
preprod-Support  | @pranaysahith | Done | 78.159.113.38
preprod-File-Drop  | @MaNe2020 | Done  | 78.159.113.32
preprod-Traffic-Gen  | WAIT | N/A  | <IP Address>
preprod-Monitoring  | WAIT | N/A  | <IP Address>

Guidelines:
- Please change the default password of the VM as instructed internally.
- Add "preprod-" as a prefix to the VM name.
- Document deviation from [instructions](https://github.com/k8-proxy/GW-proxy/tree/master/OVAs-creation).
- Test the functionality and report here the status as a comment.

Notes:
- Proxy-1 and Proxy-2 should have identical configuration and both should be configured to:
  - Use HAProxy-ICAP as the ICAP server
  - Do not rewrite URLs, use original URLs.
  - Be a reverse proxy for (Both HTTP and HTTPS): 
    - glasswallsolutions.com (Online)
    - example.local (Offline Wordpress Website)
    - gov.uk (Offline Gov.Uk Website)
    - owasp.org (Online)

- HAProxy-ICAP should be configured to use ICAP-Server-1 and ICAP-Server-2

**Comment by naderaly** [comment]
@mahnouman Preprod-MinIO vm is up and running on with IP 78.159.113.43, I've already updated the table above

**Comment by nirvishek** [comment]
@mahnouman I have deployed preprod-Wordpress on IP 78.159.113.39, and seems to be running fine. Please verify.

**Comment by svf97** [comment]
- passwords in preprod-ICAP-Server-1 and preprod-ICAP-Server-2 were changed as instructed
- names were modified as instructed

**Comment by anejaalekh** [comment]
@mahnouman For preprodproxy, instructions need to be updated

**Comment by anejaalekh** [comment]
@mahnouman  PR with updated steps 
https://github.com/k8-proxy/GW-proxy/pull/171

**Comment by MaNe2020** [comment]
@mahnouman @GINAGC preprod for FileDrop is not ready.
With provided instructions it is not possible to recreate the OVA.
If steps are followed strictly, it is not possible to connect to github and pull the repo, if network configuration is changed, after running ./deploy.sh, helm is not found and configuration is not completed.
Importing the OVA works but it has user/secret credentials. Do you want me to create preprod one with these or to wait for resolution?

**Comment by MaNe2020** [comment]
@mahnouman @GINAGC 
SOW REST aka File Drop preprod is created and it is up and running on: https://78.159.113.32/
ESXi02, IP: 78.159.113.32, name: preprod-FileDrop

VM credentials are set as per @mahnouman message.

Let me know if anything else is needed.

**Comment by top-dev-mania** [comment]
By following the below URL, I've installed the VM named preprod-Linux-Desktop, running on with IP 78.159.113.48.
https://github.com/k8-proxy/GW-proxy/blob/master/OVAs-creation/Linux-Desktop.md

I found some problems should be updated.
1. Network Configuration
 - I think it's better to following this document.
   https://github.com/k8-proxy/GW-proxy/blob/master/OVAs-creation/minio_server.md
2. Correction of the download link to OVFtools.
![image](https://user-images.githubusercontent.com/73068626/101520497-3422ef80-394a-11eb-84e3-588a0efe3730.png)

3. Run the command with the root privilege.
![image](https://user-images.githubusercontent.com/73068626/101520833-a398df00-394a-11eb-84a8-d6bafa751cad.png)

**Comment by top-dev-mania** [comment]
1. By following the below URL, I've installed the VM named preprod-Shared-Storage, running on with IP 78.159.113.49.
   https://github.com/k8-proxy/GW-proxy/blob/turenas_doc/OVAs-creation/TrueNas-OVA.md
