### ISSUE TITLE
Test Proxy OVA

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#156]
Instructions are here: https://github.com/k8-proxy/GW-proxy/blob/master/OVAs-creation/proxy-rebuild.md

**Comment by MaNe2020** [comment]
@GINAGC as tested for today demo, OVA is working good.
Documentation about creating OVA from scratch is not good, since there are some errors on the way.
Also there was some concern raised by Dinis regarding the OVA itself so this should be followed up next week.
