### ISSUE TITLE
Test Monitoring OVA

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#172]
Instructions: 
https://github.com/k8-proxy/GW-proxy/blob/91aea3b86e8e41c62b6fbe10737f15f976bb9dbf/OVAs-creation/monitoring-ova.md

**Comment by svf97** [comment]
- for installing elasticsearch:
  - before running `	sudo apt-get update && sudo apt-get install elasticsearch` please run `echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-7.x.list`

**Comment by GINAGC** [comment]
@svf97, @MaNe2020 when you finish this one, send a PR including the previous comment from Shereen.

**Comment by GINAGC** [comment]
@MaNe2020 documentation is updated now, please check again.
