### ISSUE TITLE
Test gov.uk offline website OVA

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#173]
Test gov.uk offline website OVA:
https://github.com/k8-proxy/GW-proxy/blob/37189c29677dde44e01c4f76a50092b062ffabc2/OVAs-creation/create_gov_uk_offline_site.md

Make sure that many files are tested.

**Comment by svf97** [comment]
- got this page when navigating to http://gov.uk.local 
![image](https://user-images.githubusercontent.com/60857664/101054262-5fe05700-3591-11eb-8bf9-2a71989c76c3.png)
- in SSL setup:
  - after running `openssl req -x509 -newkey rsa:4096 -keyout apache.key -out apache.crt -days 365 -nodes`, we can `ENTER` until CN is asked
- website loads when SSL is setup

**Comment by MaNe2020** [comment]
FYI this is not the correct README (from instructions): https://github.com/k8-proxy/GW-proxy/blob/37189c29677dde44e01c4f76a50092b062ffabc2/OVAs-creation/create_gov_uk_offline_site.md

I will use and update: https://github.com/k8-proxy/GW-proxy/blob/master/OVAs-creation/gov_uk_offline_site.md

And these README files are becoming a bit chaotic so we should have some naming convention.
Ex. README file should have the same title as OVA name in table, on ova creation page.

**Comment by MaNe2020** [comment]
@NourEddineX I followed the steps from https://github.com/k8-proxy/GW-proxy/blob/master/OVAs-creation/gov_uk_offline_site.md 
- /www/html both www and html folder have to be created
- When mimicking steps from the start, when trying to unzip govuk I get
![image](https://user-images.githubusercontent.com/70108899/101553294-a6c8b500-39b4-11eb-88e4-3d3b97e258d6.png)

- When trying to import the OVA, I got stuck on downloading, ca.pem.
Certificate is not present in /home folder. 
If it needs to be created before downloaded, please add to README.

- Also OVA password is still glasswall. Not as documented. That is maybe not relevant at all. 

Created PR with part of the changes: https://github.com/k8-proxy/GW-proxy/pull/231
