### ISSUE TITLE
Test SOW REST 

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#174]
Instructions:
https://github.com/NourEddineX/GW-proxy/blob/dd0ceba51ccd1f3cb266c8c656c817fec3ecff4e/OVAs-creation/SOW-REST.md

**Comment by svf97** [comment]
- got this error when running the first command 
![image](https://user-images.githubusercontent.com/60857664/101063222-404e2c00-359b-11eb-9301-a2b121bafd55.png)
resolved with `echo 'user ALL=(ALL) NOPASSWD: ALL' | sudo tee /etc/sudoers.d/user`
- run `sed -i 's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"/g' /etc/default/grub` with `sudo` 
- got this error while modifing network.yaml 
![image](https://user-images.githubusercontent.com/60857664/101065018-51983800-359d-11eb-97ba-30394419f035.png) so modified using `sudo vi /etc/netplan/network.yaml`
- you can skip the dhcp setup if you've already set up network interface when setting up the VM, if not, please run `ip a` to get your network interface and replace eth0 with it
- got this warning when running `./deploy.sh`
![image](https://user-images.githubusercontent.com/60857664/101066420-0bdc6f00-359f-11eb-8968-9185d9346ee8.png)
