### ISSUE TITLE
Test Linux desktop OVA

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#186]
Documentation: https://github.com/k8-proxy/GW-proxy/blob/master/OVAs-creation/Linux-Desktop.md

OVA link to be added soon: https://github.com/k8-proxy/GW-proxy/tree/master/OVAs-creation

**Comment by svf97** [comment]
- there were no problems following this documentation to create linux desktop OVA from scratch

**Comment by GINAGC** [comment]
@MaNe2020 see notes on this comment: https://github.com/k8-proxy/GW-proxy/issues/153#issuecomment-740792693

**Comment by MaNe2020** [comment]
@GINAGC just looking.
Also this preprod-LinuxDesktop is not running.

And I found additional issues on top of that comment. 
Waiting for @naderaly so we can go through this documentation.
