### ISSUE TITLE
Create a High-Level VMware diagram of components

### ISSUE THREAD

**Issue by michaelhidalgo** [k8-proxy/GW-proxy#189]
Create a High-Level VMware diagram of components so we can understand the relationship between those components and the respective ports.

**Comment by michaelhidalgo** [comment]
The first version is here 

![Glasswall-VMWare-Deployment-v2](https://user-images.githubusercontent.com/1732035/101071460-42e05f80-3562-11eb-977e-20a0fa316dc8.png)

**Comment by michaelhidalgo** [comment]
There will be some more interactions of this.

**Comment by GINAGC** [comment]
@michaelhidalgo anything else to add to this documentation? if not, to look for the best place to put it.

**Comment by michaelhidalgo** [comment]
Hello @GINAGC , I don't think there have been significant changes to this one, maybe we can make it better since this one was just a draft to highlight the components, maybe the graph designers can help but from an engineering point of view, I believe we should be good.

I have shared this one with @ChrisHolman, need to check with him if any enhancement was done.
