### ISSUE TITLE
Deploy and configure fluentbit on each preprod machine

### ISSUE THREAD

**Issue by faisaladnanpeltops** [k8-proxy/GW-proxy#195]
See the instruction here:
https://github.com/k8-proxy/GW-proxy/blob/master/OVAs-creation/monitoring-ova.md

**Comment by azopat** [comment]
This is done on all preprod machines.
But i think we need to include it in the ova @mahnouman  @dtollaku 
Can i take care of that ? I can do on one ova and document

**Comment by mahnouman** [comment]
yes @azopat we need to include this and also to adjust the documentation accordingly
