### ISSUE TITLE
Automation for OVAs

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#206]
Please create the below scripts, we will keep updating this table periodically:

| Script                  | Scope   | Status | Notes                                                        |
| :---------------------- | :------ | :----- | ------------------------------------------------------------ |
| Change network settings | All VMs |        | Changing the IP, subnet, gateway and DNS, of the VM primary interface |
| Change default password | All VMs |        | Force running on it on first boot                            |
| Health Check            | All VMs |        | Doing an application layer health check                      |

Draft:
Automation:
Initial setup script
Clean up script
Building VM
Deploying VM

**Comment by mahnouman** [comment]
A script to update fluentbit server information
