### ISSUE TITLE
ICAP-Client OVA (Minimal OS)

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#207]
Create an ICAP-Client OVA using the smallest possible Linux distro, maybe worth checking Photo Linux.

The OVA should include the ICAP-Client found here:
https://github.com/k8-proxy/icap-client-docker

Along with its scripts

**Comment by mahnouman** [comment]
@anejaalekh There are scripts provided with this docker to run it and to do multiple requests in parallel, I believe @DinisCruz developed those, so he might have an idea about their location in the repo

**Comment by GINAGC** [comment]
From Alekh:

_I am not able to create OVA file with photon OS. I tried but not able to create the icap-server build

VM details are as below:
esxi02
vm name: ICAP_CLIENT
login: user --> root  and password --> Gl@$$wall 

I am not deleting this server, so that someone can build on top of this_

**Comment by hongson1981** [comment]
Hi @mahnouman , @GINAGC 
I've done this task
OVA is already via link https://glasswall-sow-ova.s3-eu-west-1.amazonaws.com/vms/icap-client/icap_client.ova
PR is created already
Please help to check and merge
