### ISSUE TITLE
Documentation and next steps on Monitoring

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#209]
1.- Providing existing features list.
2.- Migrate work into GW Github repo.
3.- After these 2, we will define the next steps.

Please  include the feature list in a table similar to this:
| Feature   | Scope   | Status   | Notes         |
| :-------- | :------ | :------- | ------------- |
| feature 1 | All VMs | Develped | feature noted |
| feature 2 | SoW     | Tested   |               |
| feature 3 |         |          |               |

And do a PR for that table as part of the monitoring documentation here:
https://github.com/k8-proxy/GW-proxy/tree/master/OVAs-creation

**Comment by mahnouman** [comment]
@pranaysahith as part of this task please create a script or binary that call the ICAP-client found here: https://github.com/k8-proxy/icap-client-docker to basically do a health check on the ICAP servers, HAProxy will be configured to run this script to do sort of application layer health check.
