### ISSUE TITLE
Standardise passwords for OVAs and update documentation

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#217]
We need to ship the OVAs with standard passwords, for both the operating system and application. We may discuss internally the best combination.

**Comment by mahnouman** [comment]
@GINAGC communicated the basic idea to @michaelhidalgo in a private message.

**Comment by michaelhidalgo** [comment]
Yeah, It would be great if we could force the user to change the password on the first boot, I'm not very sure if that is possible but I have seen some commends such as change

```# chage -d 0 testuser```

If we can achieve this,  even when we ship default passwords, the customer/user will be forced to change it.

**Comment by michaelhidalgo** [comment]
AKA Password Policy for forcing this password to be changed on the first boot.

**Comment by MariuszFerdyn** [comment]
I think that during the first boot there should be a use interaction for:
1. IP
2. MASK
3. GW
4. DNS
5. new password

**Comment by GINAGC** [comment]
@michaelhidalgo please provide an update of this task. Thanks

**Comment by michaelhidalgo** [comment]
I believe the workflow proposed by @MariuszFerdyn  should work, ask a new password as the last step.

**Comment by michaelhidalgo** [comment]
Is this being scripted somewhere @MariuszFerdyn ? How is working on that one?

**Comment by michaelhidalgo** [comment]
It seems like item 5 has been addressed on https://github.com/k8-proxy/vmware-scripts/blob/main/scripts/pw-reset-onlogin/pw-reset-onlogin.sh

**Comment by MariuszFerdyn** [comment]
My latest version is here: https://github.com/k8-proxy/vmware-scripts/blob/main/scripts/BootScript.md

But later some functionality has been added: https://github.com/k8-proxy/vmware-scripts/blob/main/scripts/BootScriptWithGUI.md

**Comment by michaelhidalgo** [comment]
Has this script being tested already? If yes, we can go ahead and close this one.
