### ISSUE TITLE
Create wiki for session 2

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#224]
See table: https://github.com/k8-proxy/GW-proxy/blob/07495f9a409ac924e53b959f33934e48b7c3b053/OVAs-creation/monitoring-ova.md

We need to create a similar wiki with the detailed steps for session 2. The instructions from session 1 are: https://github.com/k8-proxy/ESXI-setup-server/wiki/VMware-Setup-session-instructions.md

When possible: include videos, script and diagrams.

**Comment by GINAGC** [comment]
@svf97 while Marija finishes testing, please create the first draft of this wiki. Thank you

**Comment by MaNe2020** [comment]
@GINAGC what is the outline for the session 2? We should use instructions from session 1 or there is a different agenda?

**Comment by GINAGC** [comment]
@MaNe2020 see the 2 tables at the bottom here: 

https://github.com/k8-proxy/ESXI-setup-server/wiki

Session 1 are these instructions: https://github.com/k8-proxy/ESXI-setup-server/wiki/VMware-Setup-session-instructions.md

We need something similar with a similar structure for the session 2.

Session 1 instructions are being updated by Samarth and Nader.
