### ISSUE TITLE
Creating SMB share

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/GW-proxy#266]
Create a SMB share with required access on the Storage (TrueNAS) pre-prod machine to support Mohit's work with the API service.

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/102222899-0ae5fe80-3f0a-11eb-821c-aa729769c3ea.png)

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/102223209-67e1b480-3f0a-11eb-82d5-385ce81f5c8c.png)

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/102223357-a24b5180-3f0a-11eb-8bef-f4e1f10bf5b5.png)

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/102223455-bee78980-3f0a-11eb-906e-447b246d5a09.png)

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/102223590-f0605500-3f0a-11eb-895d-e8e6c82f9225.png)

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/102223752-1d146c80-3f0b-11eb-8021-55203ce98e32.png)

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/102223884-4503d000-3f0b-11eb-905c-2c3bf9e5f963.png)

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/102224032-767c9b80-3f0b-11eb-8a0d-855563068030.png)
