### ISSUE TITLE
No instructions to connect Gov.uk site to a Proxy Rebuild server

### ISSUE THREAD

**Issue by ggrig** [k8-proxy/GW-proxy#278]
The "Gov.uk Setup" section at
https://github.com/k8-proxy/ESXI-setup-server/wiki/ESXi-VMware-Setup-Instructions-Session-Two
should clearly specify how Gov.uk can utilize a Proxy Rebuild server

**Comment by mahnouman** [comment]
@NourEddineX zooming into the issue, it is about providing instructions on configuring Proxy to use the offline gov.uk website

**Comment by pranaysahith** [comment]
@ggrig we need to use proxy-rebuild.ova to create a proxy for gov.uk website.
I have added instructions [here](https://github.com/k8-proxy/ESXI-setup-server/wiki/ESXi-VMware-Setup-Instructions-Session-Two#proxy-rebuild), Please try and let me know if you face any issue.

**Comment by ggrig** [comment]
Hi Pranay,
It was clear that we need proxy rebuild deployment. And we did use the corresponding OVA for that.
This is not what the issue is about. 
The issue is about what settings in Gov.UK VM are to be adjusted that will allow utilizing services provided by the proxy rebuild VM

**Comment by pranaysahith** [comment]
@ggrig I believe we don't need to configure any settings in gov.uk VM. We just need the IP address of the gov.uk VM and use in when configuring proxy rebuild VM.
@NourEddineX  let me know if I am wrong.

**Comment by mahnouman** [comment]
Hello @ggrig you do not need to do something in the offline gov.uk VM itself to make it work with the proxy, but the opposite is correct. The proxy from the gov.uk point of view is a client similar to any other client.

So basically you start by using a hosts file entry or similar to point your client machine to use the offline gov.uk, if that works and you are able to browse then modify that hosts file entry to point to the proxy, if all is good you should be still able to browse and on top of that get the files processed.
