### ISSUE TITLE
Create OVA files using Packer

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/GW-proxy#281]
The purpose of this issue is to create the OVA images using [HashiCorp Packer](https://www.packer.io/) (You may suggest alternatives). The goal is to be able to automate the process of OVA creation in order to have images with common set of tools and to reduce OVA build time.

An initial script is provided here by @NourEddineX :
https://github.com/k8-proxy/vmware-scripts/tree/main/packer

**Comment by mahnouman** [comment]
@NourEddineX please provide instructions on how to include extra packages, or replace default configuration files. 
@NourEddineX please create a file or similar that will host the common packages that we will need to be installed.

@naderaly @pranaysahith @azopat please try out to use Packer to produce your own OVA.

**Comment by NourEddineX** [comment]
> @NourEddineX please provide instructions on how to include extra packages, or replace default configuration files.
Please review [this PR](https://github.com/k8-proxy/vmware-scripts/pull/19)
> @NourEddineX please create a file or similar that will host the common packages that we will need to be installed.
You can include extra packages as needed in each projects by adding an installer command as indicated in [the README updates on this PR](https://github.com/k8-proxy/vmware-scripts/pull/19) , or if some packages is needed on all OVAs, you can add it [here](https://github.com/k8-proxy/vmware-scripts/blob/6ad162b4f609d0606c388df68ed9c9330a42f41b/scripts/config/init-config.sh#L5)
