### ISSUE TITLE
CI pipeline 

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/GW-proxy#283]
setup a CI pipeline that covers the entire flow:

- Create OVA
- Publish it to S3
- Install OVA in VMware ESXi server (from S3)
- Setup VM in ESXi
- Run health checks on deployed VM to make sure all is good

**Comment by mahnouman** [comment]
@pranaysahith please start experimenting with this.

**Comment by GINAGC** [comment]
closed with https://github.com/k8-proxy/k8-rebuild/issues/16
