### ISSUE TITLE
Install OVA in VMware ESXi server (from S3)

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#285]
Check the options to programmatically deploy an OVA to an esxi server. Please check also about how to provide VM specific instructions to the deployed OVA, for example its IP.

**Comment by nirvishek** [comment]
Done with the script to deploy ova to the esxi server either from local or from a url(e.g. s3). Working on specifying VM specific instructions to deployed OVA (taking wordpress as the testing ova).
