### ISSUE TITLE
Delete  VM process (Automate cleaning process)

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#288]
Please use [pyvmomi ](https://github.com/vmware/pyvmomi) or otherwise suggest an alternative to create an automated process to initially delete the no longer needed VMs from an ESXi server.
We can start by something very basic as identifying the VMs to be deleted by a specific comment or tag value.

You may also refer to: https://github.com/k8-proxy/k8-vmware

**Comment by GINAGC** [comment]
Hi @naderaly, @mahshaban95 please provide an update of this task.

**Comment by mahshaban95** [comment]
Hi @GINAGC , I am working on adding a feature to k8-vmware repo to be able to extract info specific to each VM on the ESXi server (.e.g notes section) and then use that feature in a script to delete the VM based on that info.

**Comment by GINAGC** [comment]
closing with https://github.com/k8-proxy/k8-rebuild/issues/39
