### ISSUE TITLE
Unit testing for VMware scripts

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#290]
Please go through the [scripts repository](https://github.com/k8-proxy/vmware-scripts), propose where unit tests can be introduced and it would worth providing an example.

You may consider any of these scripts as a starting point:
https://github.com/k8-proxy/vmware-scripts/blob/main/scripts/pw-reset-onlogin/pw-reset-onlogin.sh
https://github.com/k8-proxy/vmware-scripts/tree/main/scripts/wizard
https://github.com/k8-proxy/vmware-scripts/tree/main/scripts/cleanup

**Comment by top-dev-mania** [comment]
for : https://github.com/k8-proxy/vmware-scripts/blob/main/scripts/network/network.sh

I think it's better to add the command on the end of the file

sudo netplan apply

**Comment by GINAGC** [comment]
Ergest Imaj:
I've written the code to check the Hostname, IP, OS, and netstate and ping, and uptime

**Comment by GINAGC** [comment]
@top-dev-mania please review https://advancedweb.hu/unit-testing-bash-scripts/ to get better guidance on what is expected here. Review and let us know if this is clear.
