### ISSUE TITLE
Improve dashboards and VM information since the setup

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#291]
Hi Faisal,

We need your help to define what are the improvements to implement dashboards and VM information, from the setup of the OVA until running. Please comment with your thoughts here or in slack.

**Comment by faisaladnanpeltops** [comment]
- [ ] Automating k8s metrics endpoint 
- [ ] Update documentation

**Comment by GINAGC** [comment]
merged with https://github.com/k8-proxy/GW-proxy/issues/331
