### ISSUE TITLE
Prepare OVA documentation for automated process to wiki

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#292]
Hi Marija, 

We want to automate the process of moving documentation from the repository to the wiki. For that, we think that the best way is to split the documentation. But let us know if you have any other ideas.

Create folder per OVA and divide the MD into:
- Create OVA
- Deploy in ESXi
- How to use ESXi

**Comment by MaNe2020** [comment]
@GINAGC @mahnouman 

At the moment we have 14 OVAs.
We should move these 14th in separate folder (like OVA_README_Files) and they should have some convention in naming.
This is my suggestion. No spacing, just _ if OVA is working offline. Not sure if we should have OVA in the name, but this should be the first step.

ProxyRebuild
HAProxyICAP
HAProxyWeb
MinioServer_Offline
ICAPServer
Wordpress
SharedStorage
FileDrop
Monitoring
GovUK_Offline
TrafficGen
Support
LinuxDesktop
ICAPClient


Also I will sent few examples of the current OVAs and how I see this MDs should be structured. If you agree I will proceed with implementing this.

**Comment by GINAGC** [comment]
Hi @MaNe2020 I like the naming defined, the "OVA" is not needed, I agree.

Regarding the MDs to split, I think we should avoid having many MD files to maintain and we should have the same order in all of them. For example: 

1. Creating the OVA (this should be only internal and not needed in wiki).
2. Importing the OVA and probably together with Starting the VM on ESXi? If not, separate MDs are fine. 
3. Short description of the OVA and OVA Usage. I feel these 2 belong together. 

Let me know what you think.

**Comment by samarthdd** [comment]
@MaNe2020 @GINAGC  Let me know folder strucure once done

Rightnow my github action takes all .md files from a folder and combine it to make a wiki file

So if we have 3 folder, we can run same logic for multiple folder

**Comment by MaNe2020** [comment]
@samarthdd @GINAGC 
Here is small chart of how I plan to modify this

![OVAFlow](https://user-images.githubusercontent.com/70108899/102355306-f9553300-3fab-11eb-96c9-5b19095fd704.png)


Let me know what you think

**Comment by samarthdd** [comment]
@MaNe2020 @GINAGC 

Reading all folders under OVA_MDs and combining files except files with regex CreatingOVA

One more thing to keep in mind is order of files
in all folders either order should be same, Starting VM , OVA usage
or i can check some regex for each file so that in wiki it will copy accordingly

**Comment by GINAGC** [comment]
looks great @MaNe2020 

@samarthdd would it help to add a number at the beginning of each MD? Like a step number. Example:

1_Creating_OVA
2_Starting_Importing
3_OVA_usage

or something similar?

**Comment by samarthdd** [comment]
Yes @MaNe2020 @GINAGC That would be perfect for both readability and action. I just tested it

**Comment by samarthdd** [comment]
Its your call @GINAGC I can change it other way also if needed

**Comment by MaNe2020** [comment]
@samarthdd @GINAGC 
I created PR: https://github.com/k8-proxy/GW-proxy/pull/312
It contains structure, as discussed above.
It is done for 4 OVAs: LinuxDesktop, GovUk_Offline, SharedStorage
Please take a look and verify if this looks ok.

There is some refining to be done. 
All of these MDs should have the same structure. I will work on that later on.
This is for now, just a starting example.

**Comment by GINAGC** [comment]
@MaNe2020 looks really good, I dont have any additional feedback. I think this structure will allow us to add more MDs as needed.

**Comment by MaNe2020** [comment]
@samarthdd 
I realized while proceeding with other OVAs that 2_StartingVM_ImportingOVA is not correct name. Since this Starting VM is actually part of OVA creation, and OVA import is kind of automatic.

I will finalize this work later today, but the change is that I renamed 2_StartingVM_ImportingOVA to 2_Importing_OVA.

And I added that 3_OVA_Usage is always ending with 2 lines 
![image](https://user-images.githubusercontent.com/70108899/102629990-3d7f3980-414c-11eb-9b86-5ff321f3b45e.png)

in order to kind of separate different OVAs in the wiki. 

I will notify you once I create PR.

**Comment by MaNe2020** [comment]
@GINAGC here is the PR: https://github.com/k8-proxy/GW-proxy/pull/325, with the complete OVA-MDs folder, with all 14 OVAs having their own separate folder and all MDs being split in 3.
Have in mind that I did not verify the instructions, as that should be part of our final testing in January.
Also old MDs should be removed and devs should be instructed to use this new structure, so we avoid double work and issues later on. 

@samarthdd let me know if this all works as expected.

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/102920812-62a7db00-44b1-11eb-82ae-c2d0308413fb.png)
