### ISSUE TITLE
Document how to secure Elasticsearch and Fluent bit pipeline

### ISSUE THREAD

**Issue by michaelhidalgo** [k8-proxy/GW-proxy#296]
As we are using Fluent bit to index text-based logs (Kubernetes transactional logs), it is important to create a secure pipeline (from collection to ingestion), this way when it is deployed in VMWare, it can be secure.

Note that the solution here is two-fold:

1.  It is necessary to turn on and configure X-Pack security and User credentials in Elasticsearch.
2. It is necessary to configure the other extreme of the pipeline (Kibana, Fluent bit) so they use credentials defined in 1.

This setup will work using Basic Authentication.

**Comment by michaelhidalgo** [comment]
# Overview

Elasticsearch provides a security model via a component called X-Pack, which provides a way to protect data stored on Elasticsearch indices. This component is available by default in Elasticsearch 7 but it is not enabled.

## Enabling X-Pack on Elasticsearch

To enable X-Pack on Elasticsearch, it's required to modify the configuration file located at ``` /etc/elasticsearch/elasticsearch.yml``` to add these two configuration settings (both are required)

```yml
 xpack.security.enabled: true
 xpack.security.transport.ssl.enabled: true
```

==When X-Pack has been enabled, all the different elements of the pipeline (beats, Kibana, Logstash) will need to provide authentication credentials to be able to interact with Elasticsearch engine==

## Setting up passwords for Elasticsearch users

Elasticsearch is not longer shipped with default credentials, this is good because it was a common practice to leave default credentials, making deployments vulnerable.

Current versions of Elasticsearch provides functionality to setup credentials, this is achieved by running this command (you will be prompted to define passwords for the multiple instances of Elasticsearch)

```yml
sudo /usr/share/elasticsearch/bin/elasticsearch-setup-passwords interactive

```

Output will be :

```
Initiating the setup of passwords for reserved users elastic,apm_system,kibana,kibana_system,logstash_system,beats_system,remote_monitoring_user.
You will be prompted to enter passwords as the process progresses.
Please confirm that you would like to continue [y/N]

Enter password for [elastic]: 
Reenter password for [elastic]: 
Enter password for [apm_system]: 
Reenter password for [apm_system]: 
Enter password for [kibana_system]: 
Reenter password for [kibana_system]: 
Enter password for [logstash_system]: 
Reenter password for [logstash_system]: 
Enter password for [beats_system]: 
Reenter password for [beats_system]: 
Enter password for [remote_monitoring_user]: 
Reenter password for [remote_monitoring_user]: 
Changed password for user [apm_system]
Changed password for user [kibana_system]
Changed password for user [kibana]
Changed password for user [logstash_system]
Changed password for user [beats_system]
Changed password for user [remote_monitoring_user]
Changed password for user [elastic]

```

## Restart Elasticsearch
Now you need to restart the  Elasticsearch service so it can use the latest configuration settings.

## Setting up Kibana

Once X-Pack security has been enabled, it's required to instruct Kibana to authenticated against Elasticsearch. You need to specify the password that was setup for the username ```kibana_system``` on the previous step.

Edit the Kibana's configuration file located at ``` /etc/kibana/kibana.yml ``` and enable these two settings (Kibna.yml file should have some placeholders for this configuration, you just need to enable it.)

```yml
#kibana credentias 
elasticsearch.username: "kibana_system"
elasticsearch.password: ""
```

## Restart Kibana
You need to restart Kibana and next time you will be prompted to the form of a basic-authentication credential where you need to enter username and passwords defined on the previous step.

##  Configuring collectors (metricbeat or fluentbit )

To configure Fluent bit agents, we need to define a Fluentd bit configuration output and setup the password defined for user beats_system. This is done by using these two configuration fields:
```
HTTP_User beats_system
HTTP_Passwd your_password
```

Here is how the output looks like:

```yml

[OUTPUT]
    name  es
    match *
    host  127.0.0.1
    port  9200
    index my_index
    type  my_type
    HTTP_User beats_system
    HTTP_Passwd your_password
```

**Comment by michaelhidalgo** [comment]
Hey @faisaladnanpeltops , here is some configuration example on how to enable end-to-end basic auth on Elasticsearch.

**Comment by GINAGC** [comment]
@michaelhidalgo anything else to add to this documentation? if not, to look for the best place to put it.

**Comment by michaelhidalgo** [comment]
I think we are good to go,it is just about implementing this with @faisaladnanpeltops. Yeah let's find out a better place to put this documentation
