### ISSUE TITLE
CSV file in proxy-rebuild OVA is a folder containing html file 

### ISSUE THREAD

**Issue by ggrig** [k8-proxy/GW-proxy#324]
The OVA location s3://glasswall-sow-ova/vms/proxy-rebuild/proxy-rebuild.ova 

The folder location in the VM

glasswall@glasswall:/var/www/html/assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/838650/Ministerial_Hospitality__April_to_June_2019.csv$ ls
preview.html

**Comment by ggrig** [comment]
There may be multiple issues like that in the OVA

**Comment by ggrig** [comment]
Answering questions from Mahmoud Nouman (Upwork - TPM)

"...are you referring to the offline gov.uk OVA or the Proxy Rebuild?"
Yes, the issue is about the offline version of Gov.UK created from the OVA located in the S3 bucket.

"The "CSV is a directory and contains html file", instead of what?"
The point is that in the online version "Ministerial_Hospitality__April_to_June_2019.csv" is a regular file that can be downloaded. In the offline version, it is a directory.

"Was the csv file itself the artifact or pointing to list of artifacts from within the csv file content?"
The file is referenced in the following CSV file lists utilized for proxy testing:
https://github.com/k8-proxy/p-k8-jmeter-test-engine/blob/master/jmeter-icap/scripts/ICAP-Proxy-Site/proxyfiles.csv
https://github.com/k8-proxy/p-k8-jmeter-test-engine/blob/master/jmeter-icap/scripts/ICAP-Proxy-Site/proxysitefiles.csv

**Comment by mahnouman** [comment]
@hongson1981 please check, thank you

**Comment by mahnouman** [comment]
@NourEddineX please also check if around

**Comment by mahnouman** [comment]
Probably the correct OVA is: https://glasswall-sow-ova.s3-eu-west-1.amazonaws.com/vms/gov-uk/GovUK.ova

**Comment by hongson1981** [comment]
@mahnouman , @NourEddineX 
Look like there are some issues when we clone this website, some files become folders, trying to re- download assets.publishing.service.gov.uk again

**Comment by NourEddineX** [comment]
it appears that gov.uk.glasswall-icap.com backend has the correct document root, I'm compressing it

@mahnouman @hongson1981
