### ISSUE TITLE
Health check and configuration scripts after deployment

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#329]
Mariusz and Son Ha, to work together and implement a solution to: 
- Implement a set of scripts to validate the state of ANY VM just deployed in AWS and ESXi. 
- We will start with File-drop and ICAP OVA/AMIs. 

Related to the work done here: https://github.com/k8-proxy/k8-rebuild/issues/20

**Comment by MariuszFerdyn** [comment]
I am starting implementing to here: https://github.com/k8-proxy/vmware-scripts/tree/main/HealthCheck the following:

1. Shell Script to Install Health Check in Cron
2. Modify of Health Check to sending the results to sysloger


In that way, it will be possible to pass data to Graphana, ELK stack (Visualisation).

3. Adding to Helth Check times of responding (ping, HTTP, icap)

**Comment by hongson1981** [comment]
I am starting automate boot script with GUI following :
1. Automate create boot script for CI/CD
2. Integrate wizard.sh

**Comment by faisaladnanpeltops** [comment]
@MariuszFerdyn @hongson1981 ,

 I have a problem in parsing the pyCheck output
Can you change the output to this format:
`Dec 23 12:11:43 78.159.113.57 ping 8.8.8.8: PASS 13.23`

- Dec 23 12:11:43 : timestamp
- 78.159.113.57: host
- ping 8.8.8.8: checkpoint
- PASS: result
- 13.23: round trip time in ms

that way, I can parse the log and create json format automatically like this
```
{
              "result" => "PASS",
                "host" => "78.159.113.57",
          "@timestamp" => 2020-12-23T12:11:43.000Z,
    "syslog_timestamp" => "Dec 23 12:11:43",
                "port" => 57614,
                 "rtt" => "13.23",
         "received_at" => "2021-01-07T14:02:11.067Z",
      "syslog_program" => "ping 8.8.8.8",
                "type" => "syslog",
            "@version" => "1",
     "syslog_hostname" => "78.159.113.57",
             "message" => "<13>1 2021-01-07T14:02:10.980092+00:00 ubuntu glasswall - - [timeQuality tzKnown=\"1\" isSynced=\"1\" syncAccuracy=\"93500\"] Dec 23 12:11:43 78.159.113.57 ping 8.8.8.8: PASS 13.23",
       "received_from" => "78.159.113.57"
}
```

**Comment by MariuszFerdyn** [comment]
I will be working on that....

**Comment by GINAGC** [comment]
Updating to release v.1.2.0 to continue with the improvements like https://github.com/k8-proxy/vmware-scripts/issues/44

**Comment by hongson1981** [comment]
As @MariuszFerdyn is working on https://github.com/k8-proxy/vmware-scripts/issues/44
I will working on @faisaladnanpeltops ' request

**Comment by hongson1981** [comment]
Hi @faisaladnanpeltops 
PR https://github.com/k8-proxy/vmware-scripts/pull/48#issue-552043394 resolve your request, please chek

**Comment by GINAGC** [comment]
@MariuszFerdyn, @hongson1981 what are the next steps on these scripts? We did not review to detail in today's demos, so please share your thoughts.

**Comment by hongson1981** [comment]
Hi @GINAGC 
The next step is issue which I and @MariuszFerdyn are working on : https://github.com/k8-proxy/k8-vmware/issues/13 (Creating AWS Lambda function that execute healthcheck )
So we have 2 versions for healthcheck : 
1. Healthcheck script run directly on VM for monitoring its (Done in this issue)
2. Healthcheck script run on AWS lambda for monitoring VMs and send result to ELK ( Under developing https://github.com/k8-proxy/k8-vmware/issues/13)

**Comment by MariuszFerdyn** [comment]
I predict that during the next week there will be Lambda version of Health Check.

**Comment by GINAGC** [comment]
Thank you, then I am closing this issue! See also https://github.com/k8-proxy/vmware-scripts/issues/74 and let me know what you think there.

**Comment by MariuszFerdyn** [comment]
https://github.com/k8-proxy/vmware-scripts/pull/108 - but still some tasks to do

**Comment by GINAGC** [comment]
Closing for now, if any additional work is needed, a new task will be opened https://github.com/k8-proxy/vmware-scripts/tree/main/HealthCheck
