### ISSUE TITLE
Release repo preparation

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/GW-proxy#339]
First, please get yourself familiar with git submodules so we use it in the [releases repo](https://github.com/k8-proxy/s-k8-releases), a starting point is [this](https://www.vogella.com/tutorials/GitSubmodules/article.html#:~:text=Use%20the%20git%20submodule%20update,updates%20of%20the%20nested%20submodules.) plus what you might find on Google.

Features to be considered:

1. Identify the list of repos to be included.
2. pull particular tag or branch from remote submodule repo
3. Tag main repo once we create submodule

**Comment by mahnouman** [comment]
@pranaysahith please transplant the CI/CD code to the new repo, thanks

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/104037813-d4df2600-51fa-11eb-8759-51f197daf803.png)

**Comment by samarthdd** [comment]
![image](https://user-images.githubusercontent.com/64204445/104037934-de688e00-51fa-11eb-84a1-990d1564a34e.png)
