### ISSUE TITLE
TLS listener for ﻿k8-proxy/k8-rebuild

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/GW-proxy#341]
Add a HTTPS listener (Default external port: 443) for the mentioned service, it should be fine using a self signed certificate, please add a way (config file or similar) to easily enable/disable the port and also to force only the HTTPS port (Disabling http).

**Comment by yardenshoham** [comment]
Closed in https://github.com/k8-proxy/k8-rebuild/pull/52
