### ISSUE TITLE
Document how to use the REST API using curl for ﻿k8-proxy/k8-rebuild

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/GW-proxy#342]
Possibly embedding this into a Swagger interface. For example: https://stackoverflow.com/questions/21282100/generate-curl-command-of-swagger

**Comment by GINAGC** [comment]
curl examples are naturally embedded into swagger. Making an API request with swagger automatically creates a curl example that is ready to be used in the terminal. 

swagger is available here https://k8-proxy.github.io/k8-rebuild-rest-api/#/

Closing issue.

**Comment by GINAGC** [comment]
@mahshaban95 I have clarified this one with @mahnouman and reopened for you.

**Comment by GINAGC** [comment]
@mahshaban95 please share an update of this task, can you have this completed this week?

**Comment by mahshaban95** [comment]
@GINAGC  Yes. The main structure of the script is done and some of the endpoints were included into it. I am just having a little difficulty mapping the curl code to the bash script for the rest of the endpoints but I think it would be completed by the end of this week.

**Comment by GINAGC** [comment]
Issue moved to [k8-proxy/k8-rebuild-rest-api #33](https://github.com/k8-proxy/k8-rebuild-rest-api/issues/33) via [**ZenHub**](https://www.zenhub.com/)
