### ISSUE TITLE
Custom endpoint to add to the solution which will also convert a json file to XML

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/GW-proxy#343]
we will need to write a custom endpoint to add to the solution which will also convert a json file to XML file (they have a jar file that they will provide which we need to use to do this). This should be done on a docker container that is able to do this.

This is for: ﻿k8-proxy/k8-rebuild

**Comment by GINAGC** [comment]
Issue moved to [k8-proxy/k8-rebuild-rest-api #30](https://github.com/k8-proxy/k8-rebuild-rest-api/issues/30) via [**ZenHub**](https://www.zenhub.com/)
