### ISSUE TITLE
Integrate fail2ban

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/GW-proxy#344]
Follow the steps here to implement fail2ban:
https://github.com/k8-proxy/GW-proxy/issues/332

fail2ban should be part of the default releases

**Comment by naderaly** [comment]
Steps tested and working.
Creating bash script so fail2ban service with preset settings is built into the packer when we are various images
![image](https://user-images.githubusercontent.com/58347752/104023620-992c6800-51ca-11eb-903c-0451cb76dc79.png)

**Comment by michaelhidalgo** [comment]
Hey @naderaly  can we make sure this step is also included? That way if the system reboots for some reason, fail2ban service will start automatically.

```
Ensure fail2ban runs at the system startup (this is important in the event the system reboot) running systemctl enable fail2ban.service command:
systemctl enable fail2ban.service

```

**Comment by naderaly** [comment]
Hello @michaelhidalgo yes sure

**Comment by naderaly** [comment]
@mahnouman , The following PR contains file with steps to be add to the end of each setup.sh file before the packer build, so file2ban service become installed and enabled in the target image.
https://github.com/k8-proxy/vmware-scripts/pull/47

**Comment by mahnouman** [comment]
Hello @naderaly is there any of @michaelhidalgo points not covered in the [PR](https://github.com/k8-proxy/vmware-scripts/pull/47/files)? Thanks

**Comment by naderaly** [comment]
Hello @mahnouman all covered

**Comment by GINAGC** [comment]
@naderaly is there any work left here or should we close it?

**Comment by GINAGC** [comment]
work is done, closing
