### ISSUE TITLE
Github repositories administration

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/GW-proxy#347]
As preparation to manage and coordinate work for the Github repositories, please spend an hour or two getting familiar with the github repositories for both those two organizations:
https://github.com/k8-proxy

You can ignore repositories which do not have activities older than two months (Not updated since November 1st), then create a google sheets table of these repositories, one column is the repo name, then repo last update date then whether if it is missing a readme file or not.

**Comment by Mehasseb** [comment]
[https://docs.google.com/spreadsheets/d/1intVZiRbXkvuZ0r7uoqnzdm9vc51Yovi0UQSvMw7_Lc/edit?usp=sharing](url)

**Comment by dtollaku** [comment]
@Mehasseb can you paste the URL of google sheet, the one above redirects to github

**Comment by Mehasseb** [comment]
https://docs.google.com/spreadsheets/d/1intVZiRbXkvuZ0r7uoqnzdm9vc51Yovi0UQSvMw7_Lc/edit?usp=sharing

**Comment by Mehasseb** [comment]
https://docs.google.com/spreadsheets/d/1intVZiRbXkvuZ0r7uoqnzdm9vc51Yovi0UQSvMw7_Lc/edit?usp=sharing

**Comment by Mehasseb** [comment]
https://docs.google.com/spreadsheets/d/1intVZiRbXkvuZ0r7uoqnzdm9vc51Yovi0UQSvMw7_Lc/edit?usp=sharing


edited link
