### ISSUE TITLE
user acceptance testing for UI Load generation tool

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#356]
Testing of UI Load generation tool using instructions located at: https://github.com/k8-proxy/aws-jmeter-test-engine/blob/master/jmeter-icap/instructions/How-to-generate-Scaled-Load-via-UI.md ;

**Comment by svf97** [comment]
The first mentioned URL doesn't redirect anywhere https://github.com/k8-proxy/aws-jmeter-test-engine/README.MD
