### ISSUE TITLE
Manage accounts and passwords

### ISSUE THREAD

**Issue by dtollaku** [k8-proxy/GW-proxy#358]
Find a solution that works to manage and share all the urls, accounts and passwords used by the multiple servers and UIs that we have
- Shared Folders in LastPass is a good option
- We have currently one private repo that contains some info we can start with this one. (https://github.com/k8-proxy/k8-secrets)

**Comment by GINAGC** [comment]
Task on hold, removing assigned people.

**Comment by GINAGC** [comment]
We will open a support ticket for IT.
