### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/GW-proxy#360]
We are using [Github Actions](https://github.com/features/actions) for [CI/CD](https://www.infoworld.com/article/3271126/what-is-cicd-continuous-integration-and-continuous-delivery-explained.html), please get yourself familiar with it then we will append the repositories sheet with what Github Actions are there for each repo and what they are doing and whether they are broken or working.

**Comment by aduvukace** [comment]
@GINAGC this task is complete
