### ISSUE TITLE
Improve documentation for ICAP / File drop eval

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#362]
For the following documentation: https://github.com/k8-proxy/glasswall-servers-eval/wiki

**Add the documentation about how to import OVA into AWS documentation:**
1.- How to import OVA into AWS, very detailed steps from the step of downloading the OVA from a public link until it is fully imported and configured. (Please create a new page for this)
2.- Documentation how to install and use the OVA
3.- All details on how to get it up and running, which ports need to be exposed, any configuration needed, etc. 
4.- Default credentials included for the management UI, for the VMs, and any other credentials needed.
5.- Add end to end video showing this deployment. 

**Make sure that for the above, a new ESXi server is used.**

**Prepare 2 live instances to be always available (File drop and ICAP server)**

**Validate issue about password update is now fixed:** https://glasswallsolu-qbp1117.slack.com/archives/C01EE93USCV/p1612541684113600

**Comment by MaNe2020** [comment]
@GINAGC 
couple of questions:
1. OVA cannot be imported in AWS as such. OVA is just used to create AMI and then AMI is used further. Should we document this as such? It would be one line just on how to transfer OVA to AMI so not sure if we need separate page?
2. This is referring to ESXi setup?
3. clear
4. Should we add credentials in wiki itself? Should we expose that? Or there is some other way this can be done.

Also, please share new ESXi if avl.

**Comment by MaNe2020** [comment]
And also @GINAGC it would be great to have AMI and OVA public.

**Comment by GINAGC** [comment]
1.- The new OVA was created with Ubuntu 18 and it should work to import in AWS with that version. So we need to cover 3 scenarios:

- Deploy ICAP/File drop in AWS using AMI in AWS
- Deploy ICAP/File drop in AWS using OVA in AWS
- Deploy ICAP/File drop in AWS using OVA in ESXi

2.- For the 3 scenarios above, more applicable for scenarios 2 and 3. 

4.- I am not sure, I will back to you.

**Comment by MaNe2020** [comment]
@aduvukace this is almost done. We just have few things to finalized.

**Comment by svf97** [comment]
@aduvukace we're only missing the AWS OVA due to permission issues

**Comment by svf97** [comment]
@aduvukace Updated wiki on https://github.com/k8-proxy/glasswall-servers-eval/wiki

**Comment by MaNe2020** [comment]
@aduvukace, @svf97 did final check of doc and we should have everything ready.
Checked how to export wiki as PDF.
Rest of the work is done.
