### ISSUE TITLE
Setup proxy for 4 websites (sales request)

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#365]
·        glasswallsolutions.com - Nader
·        engineering.glasswallsolutions.com - Alekh
·        owasp.org - Yarden
·        gov.uk - ready

**Comment by anejaalekh** [comment]
@GINAGC Proxy for glassworksolutions.com is up and running on following instance:
https://eu-west-1.console.aws.amazon.com/ec2/v2/home?region=eu-west-1#InstanceDetails:instanceId=i-04820952d73b4e222

https://glasswallsolutions.com.glasswall-icap.com/wp-content/uploads/2020/01/Glasswall-d-FIRST-Technology.pdf
https://glasswallsolutions.com.glasswall-icap.com

**Comment by yardenshoham** [comment]
https://owasp.org.glasswall-icap.com/
https://owasp.org.glasswall-icap.com/www-pdf-archive/OWASP_Top_10-2017_%28en%29.pdf.pdf

**Comment by naderaly** [comment]
Proxing engineering.glasswallsolutions.com Done 
https://engineering.glasswallsolutions.com.glasswall-icap.com/
