### ISSUE TITLE
OVA security assessment  - TCP dump evidence

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#366]
The customer has requested to include TCP dump evidence, please prepare it and add it as a separate section to the PDF report you are preparing.

**Comment by michaelhidalgo** [comment]
Sounds good, I will walk the test scenarios and show those results.

**Comment by michaelhidalgo** [comment]
Hi @GINAGC , @dinis-cruz-gw  This has been tested:

As you can see during the Tcpdump capture, there were not outbound traffic collected:

![TCPDump](https://user-images.githubusercontent.com/1732035/108900813-b2a13c00-75df-11eb-8953-f4f288cecd60.png)

![aws](https://user-images.githubusercontent.com/1732035/108900820-b46aff80-75df-11eb-9e6c-7f1c4a0acad1.png)

However, the ICAP endpoint seems to have some issues and I'll need some help trying to troubleshoot it. When using the load testing tool 100% requests fails. I will hang on until make sure it is operational to run this tests again.

**Comment by GINAGC** [comment]
Thanks @michaelhidalgo, if this does not work today and we need the team to check, please update the PDF anyway with the videos and description, so we can send that version.
