### ISSUE TITLE
OVA storage evidence

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#367]

**Comment by MariuszFerdyn** [comment]
DOC created and shared.

**Comment by GINAGC** [comment]
Document shared by Mariusz:
https://hcompl-my.sharepoint.com/:w:/g/personal/mariusz_ferdyn_h_com_pl/ESgg7TwEWLtHjOBlY9RLjrUBhwcVB4ADTbZPgxHl0h7I9w?rtime=Zs89Bx3U2Eg

Next steps: make sure that those requirements also exist in the Compliant Kubernetes version of the AMI.

**Comment by GINAGC** [comment]
@MariuszFerdyn we got feedback from the customer on this topic, please review:

Answer the following questions and provide screenshot evidence for each of them:

1.- Can you provide more information on where files are stored in the OVA and show they are not globally writeable?
2.- I assume you are using local storage volumes with a standard K8s install? 
3.- Are there any other files outside of the k8s deployment? 
4.- When I submit a file to the ICAP or File Drop Server, where does it go?

**Comment by MariuszFerdyn** [comment]
information has been added.

**Comment by GINAGC** [comment]
Closing task, evidence sent to the customer
