### ISSUE TITLE
Sharepoint demo

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#368]
3.- Setup file Handler setup in O365 subscription https://k8-proxy.github.io/k8-proxy-documentation/docs/websites/sharepoint/cloud/file-handler-dotnetfx-install/ in this sharepoint: https://glasswalldemo.sharepoint.com/_layouts/15/sharepoint.aspx - @gurunathg 

4.- https://saaspoc1.sharepoint.com/ proxy as it was done before, here is a demo video.
https://glasswallsolu-qbp1117.slack.com/archives/C01DDEEV9K7/p1605890986022100?thread_ts=1605222258.018700&cid=C01DDEEV9K7 - @pranaysahith

**Comment by pranaysahith** [comment]
Created ec2 instance with proxy for https://saaspoc1.sharepoint.com/ and shared the details in the channel
