### ISSUE TITLE
Sharepoint file Handler setup in O365 subscription

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#370]
1.- Review the following documentation and code, repeat implement in assigned sharepoint.

**Extension:**
•Hides default Download button of SharePoint
•Developed as SPFX package
•Codebase and doc: https://github.com/k8-proxy/gp-sharepoint-plugins/tree/main/Online/glasswall-hide-download-ext
•Workflow: https://github.com/k8-proxy/gp-sharepoint-plugins/actions?query=workflow%3A%22O365+HideDownloadExtension+Workflow%22

**Add File Handler:**
•M365 Custom File Handler
•NET 5 based Web App secured with Active Directory
•Codebase and documentation: https://github.com/k8-proxy/gp-sharepoint-plugins/tree/main/Online/glasswall.o365.filehandler/Net5
•Workflow: https://github.com/k8-proxy/gp-sharepoint-plugins/actions?query=workflow%3A%22O365+FileHandler+Workflow%22

Documentation: https://k8-proxy.github.io/k8-proxy-documentation/docs/websites/sharepoint/cloud/file-handler-net5-install

**Comment by pranaysahith** [comment]
Created ec2 instance with proxy for saaspoc1.sharepoint.com and updated the channel with details

**Comment by gurunathg** [comment]
![image](https://user-images.githubusercontent.com/17300331/108088430-73826080-709e-11eb-9d7d-40ebefeec015.png)
@GINAGC  Getting error when trying to run project. Also unable to generate required API Key.

**Comment by gurunathg** [comment]
As discussed with @GINAGC , a session will be scheduled for next week to get a walkthrough and understanding

**Comment by MaNe2020** [comment]
@gurunathg @GINAGC pls include both me and @Lestat06 for the session.
As reviewed earlier, SharePoint setup and documentation has a lot of complexity and possibilities so it would be great to have clear path.

**Comment by GINAGC** [comment]
Work completed.
