### ISSUE TITLE
Setup file Handler setup in sharepoint on-prem

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#372]
**SharePoint Solution Package (WSP):**
•HttpHandler to intercept Downloads & Uploads
•Developed as WSP package
•Codebase: https://github.com/k8-proxy/gp-sharepoint-plugins/tree/main/SelfHosted/src
•Workflow: https://github.com/k8-proxy/gp-sharepoint-plugins/actions?query=workflow%3A%22SelfHosted+FileHandler+Workflow%22

Documentation: https://k8-proxy.github.io/k8-proxy-documentation/docs/websites/sharepoint/self-hosted/export-ova-aws

**Comment by MaNe2020** [comment]
@GINAGC @Lestat06 it would be great to have some intro or KT before starting with this

**Comment by GINAGC** [comment]
@MaNe2020 sure, I will schedule something for next week with the team involved.

**Comment by MaNe2020** [comment]
@GINAGC doc link is not valid, I suppose this one should be used instead: https://k8-proxy.github.io/k8-proxy-documentation/docs/websites/sharepoint/server/sharepoint-server-solution-deployment/

And can we get edit rights for these pages or their content can be changed somewhere else?
There are few non working links on page itself.

**Comment by GINAGC** [comment]
@MaNe2020 yes, I think that was because the links changed a bit. 

The repo for that wiki is https://github.com/k8-proxy/k8-proxy-documentation and you should have access.

**Comment by GINAGC** [comment]
Work completed
