### ISSUE TITLE
Sharepoint proxy QA including all file types

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#376]
1.- Test file upload and validate it is processed by ICAP server (you will need lens plugged to the ICAP server, you can ask Faisal or Pranay about how to do this).
2.- Test download file and validate that it is correctly rebuilt.
3.- Repeat the process for the supported file types.
4.- Also test uploading and downloading in batches of files. 

Proxy sharepoint:  https://saaspoc1.sharepoint.com,

![image (2)](https://user-images.githubusercontent.com/70196799/108379616-64b6bd80-7206-11eb-9584-6252114e9137.png)

**Comment by MaNe2020** [comment]
@GINAGC is this https://saaspoc1.sharepoint.com/ always avl?

**Comment by GINAGC** [comment]
@MaNe2020 that is the plan now, it should be always up for sales demos.
