### ISSUE TITLE
Review documentation from all repos and organise into one master repository

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#381]
This task is to review all repos from K8 https://github.com/k8-proxy/, identify which documentation we have on MD or wiki on each of them.

Create a document with this analysis.

After that, we will organize it and add the documentation references in one main repository.

**Comment by GINAGC** [comment]
@dtollaku please comment if I missed anything.

**Comment by MaNe2020** [comment]
@GINAGC should we include just the ones starting with K8 or all 119 of them?

**Comment by GINAGC** [comment]
all 119, but Shereen is already in progress with this - https://docs.google.com/spreadsheets/d/1bFBgc5bicUcHs1QDlnPu2KbwldsHc63NpVlApmC1hWk/edit?ts=60409fab#gid=1597475488

I think you can skip this task @MaNe2020

**Comment by GINAGC** [comment]
Hi @svf97 where we are on the next step on this task? regarding on defining the documentation categories and structure.

**Comment by svf97** [comment]
@GINAGC it's a work in progress, but initial categorization can be found in same sheet, second tab
