### ISSUE TITLE
Review documentation wiki for customers

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#385]
Hi Kerem,

The task is to review all the pages added here: https://k8-proxy.github.io/k8-proxy-documentation/  and review grammar, technical details needed, if anything is not clear or more details need to be added. Also, any improvement in the structure of the documentation or the pages in general.

Any changes need to be done on this repo: https://github.com/k8-proxy/k8-proxy-documentation and the updates will be reflected on the link above after merges.

**Comment by kerempg** [comment]
hello,
minor changes (spacing, punctuation, making substantial words bold, bulleting, numbering, capitalization of letters, creating headings, changing URL of the broken links) are pull requested.
