### ISSUE TITLE
Get a daily list of all EC2 instances used by everybody and make daily reports

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/GW-proxy#387]
Get a daily list of all EC2 instances used by everybody and map out :

1. project responsible for it
2. mode (24h, development only, load testing)
3. deployment mode: Auto Scaling group, GitHub action, manually
4. cost

**Comment by Girish-pingala** [comment]
Report has been shared in the channel.

**Comment by dtollaku** [comment]
What is the process you did is it manually created?

**Comment by Girish-pingala** [comment]
Yes, it is manually created.

**Comment by dtollaku** [comment]
We need this to be automated, since we need this report daily

**Comment by GINAGC** [comment]
@dtollaku I agree. @Girish-pingala can this be automated?

**Comment by Girish-pingala** [comment]
@GINAGC @dtollaku , Report was created by fetching data from different tools within AWS and then some excel work to keep the data in single sheet. We are not getting data from single tool otherwise it could have been automated or downloaded whenever required.

**Comment by GINAGC** [comment]
@gurunathg, @Girish-pingala any tools that you recommend to accomplish the automation of this report?

**Comment by Girish-pingala** [comment]
@GINAGC , I will try to check and get back to you. 
@gurunathg , if you know any then please suggest.
