### ISSUE TITLE
Review issue with ttps://www.gov.uk.glasswall-icap.com/ proxy and delete https://www.gmhsc.org.uk.glasswall-icap.com/ (not needed anymore)

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/GW-proxy#388]
Review issue with ttps://www.gov.uk.glasswall-icap.com/ proxy and delete https://www.gmhsc.org.uk.glasswall-icap.com/ (not needed anymore)

**Comment by gurunathg** [comment]
Deleted https://www.gmhsc.org.uk.glasswall-icap.com/
WIP for identifying root cause for www.gov.uk.glasswall-icap.com
