### ISSUE TITLE
Finish updating pipelines after incident

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/GW-proxy#390]
- we have updated the ck8icap+cloudSDK pipeline and k8icap+cloudsdk pipeline 2:11
- there are two pipelines - plain icap - ubuntu and centos that are to be update

**Comment by gurunathg** [comment]
Completed updating of below pipelines:

- Icap Ubuntu - https://github.com/k8-proxy/GW-Releases/tree/main
- Icap Centos -  https://github.com/k8-proxy/GW-Releases/tree/icap-centos
- Icap Ubuntu+cs-api - https://github.com/k8-proxy/GW-Releases/tree/cs-api-k8icap

With this, all pipelines have been updated

**Comment by gurunathg** [comment]
Icap Ubuntu+cs-api: https://github.com/k8-proxy/GW-Releases/actions/runs/820323197
ical Ubuntu : https://github.com/k8-proxy/GW-Releases/actions/runs/819705085
