### ISSUE TITLE
Replace filedrop from 63.33.49.111 to use the latest version.

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/GW-proxy#394]
Deploy the GW Cloud SDK + filedrop on CK8s with release: https://github.com/k8-proxy/k8s-compliant-kubernetes/releases/tag/v0.1.2 (it has to be with any of these AMIs)

This deployment needs to be in the EAP AWS account under the subdomain of [labs.glasswallsolutions.com](labs.glasswallsolutions.com) and we should use https.

**Comment by gurunathg** [comment]
Completed deployment of Cluster. To be done: SSL certificate

**Comment by GINAGC** [comment]
@Lestat06, @svf97 this filedrop will be used for demos, please do some testing that there is not any issue rebuilding files: https://labs.glasswallsolutions.com/

**Comment by Lestat06** [comment]
@GINAGC Files we tested till now can be found [here](https://docs.google.com/spreadsheets/d/1rDX1fbCEDNaBQ3ap6GeHHvvmU13xaEDkd2xieqkIuqI/edit?usp=sharing)
P.S today the API is not working
FYI @svf97
