### ISSUE TITLE
Mapping and cleanup of repositories in K8-proxy

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#414]
@svf97 please create a mapping in spreadsheet of all repositories here https://github.com/k8-proxy and add a column with the last time that they were updated, so we can decide which ones start archiving.

**Comment by svf97** [comment]
@GINAGC sheet shared on slack

**Comment by dtollaku** [comment]
@svf97 can you paste the link of the spreadsheet here as well.

**Comment by svf97** [comment]
@dtollaku https://docs.google.com/spreadsheets/d/1KXw7u96EBlbmbLbc_-Px2RFjbWnGt88pFBkVo4xt8A8/edit#gid=0
