### ISSUE TITLE
Upgrading process for GW Cloud SDK

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#415]
- Document how to upgrade a deployed version
- anything else?

**Comment by GINAGC** [comment]
@gurunathg P2 in case that you have a chance for this week.

**Comment by gurunathg** [comment]
For upgrading cs-api in an existing deployment, below two commands to be executed:
```
git clone https://github.com/k8-proxy/cs-k8s-api && cd cs-k8s-api
  helm upgrade --install -n icap-adaptation rebuild-api --set k8s_version=1.18 infra/kubernetes/chart  --atomic
```

A new run from https://github.com/k8-proxy/k8s-compliant-kubernetes/actions/workflows/complaint-k8s-CloudSDK.yaml can be triggered to generate new AMI with updated cs-api

**Comment by GINAGC** [comment]
@svf97 please test the above commands and document detailed steps on a new page under GW Cloud SDK section https://k8-proxy.github.io/k8-proxy-documentation/docs/products/gw%20cloud%20sdk/a-overview
