### ISSUE TITLE
Programatically update wiki with website projects information

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#87]
The following page was created to track the latest information on the website projects: https://k8-proxy.github.io/k8-proxy-documentation/docs/dashboards/websites/production

The repository for this wiki is: https://github.com/GINAGC/k8-proxy-documentation

**The goal of the task:**
1) We now want to have all these data points in a JSON file for all the website projects. 
2) This should be done with Python and with Github actions.
3) Populate all the latest information to the page: https://k8-proxy.github.io/k8-proxy-documentation/docs/dashboards/websites/production (for now, for testing purposes, create a separate page on this wiki).

**Start with the following projects:**
https://github.com/k8-proxy/gp-engineering-website
https://github.com/k8-proxy/gp-glasswallsolutions-website
https://github.com/k8-proxy/gp-emma-dataport-website
https://github.com/k8-proxy/gp-uk-zones-com
https://github.com/k8-proxy/gp-owasp-website

**Expected information from JSON:**
Website name
Outcome URL
IP
Flavor
Open ports
OS
Infrastructure
Provisioning
Container engine

**Comment by mahnouman** [comment]
Info
The wiki page to be updated is this one:
https://github.com/k8-proxy/k8-proxy-documentation/blob/master/docs/dashboards/websites/production.md

**Comment by GINAGC** [comment]
@hanyhesham, @silvanayousry, @yardenshoham, @top-dev-mania this task is paused because we have other priorities. Please stop any work here.
