### ISSUE TITLE
Create plantuml diagram for OVAs

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-proxy#98]
- Based on instructions here: https://github.com/k8-proxy/GW-proxy
- 1 diagram per OVA (4 in total)

**Comment by baker371** [comment]
![ICAP_server_OVA](https://user-images.githubusercontent.com/8102313/99725247-de36f680-2ac5-11eb-8713-4616d1c7cdce.png)

**Comment by baker371** [comment]
![Glasswall_Engineering_OVA](https://user-images.githubusercontent.com/8102313/99725292-f0b13000-2ac5-11eb-899d-311f4291ead3.png)

**Comment by baker371** [comment]
![Minio_Server_OVA](https://user-images.githubusercontent.com/8102313/99834657-91f6bf80-2b74-11eb-9fbe-a80b495c1972.png)

**Comment by baker371** [comment]
![Minio_Proxy_OVA](https://user-images.githubusercontent.com/8102313/99837199-3dedda00-2b78-11eb-9ff4-8e113e3578ba.png)
